In [13]:
from camcom import ImageCache
import numpy as np
import io
from PIL import Image
from matplotlib import pyplot as plt
from subprocess import Popen, PIPE
import time 

ic = ImageCache()
w, h = 640, 480

#libcamera-raw --width 640 --height 400 ---n --framerate 120 -o mem://
# p = Popen(["libcamera-raw", "--width", "640", "--height", "400" "--framerate", "120", "---n", "-o", "mem://"], shell=True, stdout=PIPE)
# p = Popen(["libcamera-hello --list"], shell=True, stdout=PIPE, stdin=PIPE)
p = Popen(["libcamera-raw -t 1000 --width 640 --height 400 ---n --framerate 120 -v"], shell=True, stdout=PIPE)

while True:
    time.sleep(1)
    output = p.stdout.readline()
    print(output)
    if output == '' and p.poll() is not None:
        break
    if output:
        print(output.strip())
rc = p.poll()
print(rc)

"""
for line in iter(p.stdout.readline, ''):
    time.sleep(1)
    print(line.strip())
    image_data = ic.get("1658758455890")
    image = Image.frombytes('L', (w,h), image_data, 'raw')
    # image.save("./test.bmp")
    arr = np.array(image.getdata()).reshape(image.size[0], image.size[1], 1)
"""

Options:
    verbose: 0
    info_text:#%frame (%fps fps) exp %exp ag %ag dg %dg
    timeout: 1000
    width: 640
    height: 400
    output: 
    post_process_file: 
    rawfull: 0
    preview: none
    qt-preview: 0
    transform: identity
    roi: all
    metering: centre
    exposure: normal
    ev: 0
    awb: auto
    flush: false
    wrap: 0
    brightness: 0
    contrast: 1
    saturation: 1
    sharpness: 1
    framerate: 120
    denoise: cdn_off
    viewfinder-width: 0
    viewfinder-height: 0
    tuning-file: (libcamera)
    lores-width: 0
    lores-height: 0
    mode: unspecified
    viewfinder-mode: unspecified
    bitrate: 0
    profile: 
    level:  
    intra: 0
    inline: 0
    save-pts: 
    codec: h264
    quality (for MJPEG): 50
    keypress: 0
    signal: 0
    initial: record
    split: 0
    segment: 0
    circular: 0
Raw stream: 640x400 stride 640 format NV12
Viewfinder frame 0
libcamera-raw: symbol lookup error: libcamera-raw: undefined symbol: _ZNK9libcamera11C

b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''
b''


KeyboardInterrupt: 

In [2]:
image_data = ic.get("1658758608794")

image = Image.frombytes('L', (w,h), image_data, 'raw')
image.save("./test.bmp")

arr = np.array(image.getdata()).reshape(image.size[0], image.size[1], 1)
print(arr)

[[[ 85]
  [ 85]
  [ 90]
  ...
  [ 68]
  [ 64]
  [ 68]]

 [[ 68]
  [ 65]
  [ 65]
  ...
  [ 94]
  [ 98]
  [ 97]]

 [[ 97]
  [100]
  [ 96]
  ...
  [110]
  [104]
  [109]]

 ...

 [[127]
  [127]
  [127]
  ...
  [127]
  [127]
  [127]]

 [[127]
  [127]
  [127]
  ...
  [127]
  [127]
  [127]]

 [[127]
  [127]
  [127]
  ...
  [127]
  [127]
  [127]]]
