In [65]:
from camcom import ImageCache
import numpy as np
import io
from PIL import Image
from matplotlib import pyplot as plt

ic = ImageCache()
w, h = 640, 480

image_data = ic.get("1658750257845")

image = Image.frombytes('L', (w,h), image_data, 'raw')
print(image)
image.save("./test.bmp")

arr = np.array(image.getdata()).reshape(image.size[0], image.size[1], 1)

print(arr)
exit()
decoded = np.frombuffer(image_data, dtype=np.dtype("S6"))
print(decoded.shape)
decoded = np.reshape(decoded, (w, h))
print(decoded.shape)
print(decoded)


<PIL.Image.Image image mode=L size=640x480 at 0x7F567608E0>
[[[125]
  [125]
  [126]
  ...
  [ 86]
  [ 83]
  [ 84]]

 [[ 85]
  [ 87]
  [ 86]
  ...
  [106]
  [105]
  [105]]

 [[106]
  [106]
  [105]
  ...
  [125]
  [126]
  [122]]

 ...

 [[113]
  [110]
  [107]
  ...
  [201]
  [201]
  [201]]

 [[201]
  [201]
  [201]
  ...
  [193]
  [194]
  [195]]

 [[194]
  [194]
  [194]
  ...
  [ 81]
  [ 72]
  [ 72]]]
(76800,)


ValueError: cannot reshape array of size 76800 into shape (640,480)

: 